export const skillData = [
  { title: "Html", img: "html.png" },
  { title: "Css", img: "css.png" },
  { title: "Javascript", img: "javascript.png" },
  { title: "JQuery", img: "jquery.png" },
  { title: "React", img: "react.png" },
  { title: "Redux", img: "redux.png" },
  { title: "Sass", img: "sass.png" },
  { title: "Bootsrap", img: "bootstrap.png" },
  { title: "Material UI", img: "materialui.png" },
  { title: "Ant Design", img: "antd.png" },
  { title: "Bitbucket", img: "bitbucket.png" },
  { title: "Nextjs", img: "nextjs.png" },
  { title: "Git", img: "git.png" },
  { title: "Github", img: "github.png" },
  { title: "Gitlab", img: "gitlab.png" },
  { title: "Jira", img: "jira.png" },
  { title: "Pug", img: "pug.png" },
  { title: "Sdlc", img: "sdlc.png" },
  { title: "Next UI", img: "nextui.png" },
  { title: "DevExpress ", img: "devexpress.png" },
  { title: "Npm", img: "npm.png" },
  { title: "Yarn", img: "yarn.png" },
  { title: "Responsive", img: "responsive.png" },
  { title: "Agile", img: "agile.png" },
];

export const brandData = [
  { title: "Coral Travel", href: "https://www.coraltravel.com/", img: "coraltravel.png" },
  { title: "Ziraat Katilim", href: "https://www.ziraatkatilim.com.tr/", img: "ziraatkatilim.png" },
  { title: "İstikbal", href: "https://www.istikbal.com.tr/", img: "istikbal.png" },
  { title: "Emlak Katilim", href: "https://www.emlakkatilim.com.tr/", img: "emlakkatilim.png" },
  { title: "Zorlu", href: "https://www.zorlu.com.tr/", img: "zorlu.png" },
  { title: "Bonus Piu", href: "https://www.bonuspiu.com.tr/", img: "bonuspiu.png" },
  { title: "Koç Sistem", href: "https://www.kocsistem.com.tr/", img: "kocsistem.png" },
  { title: "Tüpraş", href: "https://www.tupras.com.tr/", img: "tupras.png" },
  { title: "Opet Fuchs", href: "https://www.opetfuchs.com.tr/tr/", img: "opetfuchs.png" },
  { title: "GoTurkiye", href: "https://goturkiye.com/", img: "goturkey.png" },
  { title: "Hediyelik Karakalem", href: "https://www.hediyelikkarakalem.com/", img: "hediyelikkarakalem.png" },
  { title: "Volkswagen", href: "https://www.vw.com.tr/", img: "volkswagen.png" },
  { title: "Erciyes Anadolu Holding", href: "https://www.erciyesanadolu.com/", img: "erciyesanadolu.png" },
  { title: "Hes Kablo", href: "https://www.hes.com.tr/", img: "heskablo.png" },
  { title: "Sütaş", href: "https://www.sutas.com.tr/", img: "sutas.png" },
  { title: "Bonus", href: "https://www.bonus.com.tr/", img: "bonus.png" },
  { title: "Doqu Home", href: "https://www.doquhome.com.tr/", img: "doquhome.png" },
  { title: "Akyatırım", href: "https://www.akyatirim.com.tr/", img: "akyatirim.png" },
  { title: "Garantibbva Ticari Kartlar", href: "https://www.garantibbvaticarikartlar.com/", img: "garantiticarikartlar.png" },
  { title: "Türk Telekom Prime", href: "https://www.turktelekomprime.com/", img: "turktelekomprime.png" },
  { title: "Kalkınma Yatırım Bankası", href: "https://kalkinma.com.tr/", img: "kalkinma.png" },
  { title: "Gümüşsuyu Halı", href: "https://www.gumussuyu.com.tr/", img: "gumusuyu.png" },
  { title: "Centurion", href: "https://www.americanexpress.com/en-us/account/centurion/login?DestPage=https%3A%2F%2Fwww.americanexpress.com%2Fus%2Fbenefits%2Fcenturion", img: "centurion.png" },
  { title: "Garantibbva", href: "https://www.garantibbva.com.tr/", img: "garantibbva.png" },
  { title: "Coraltg", href: "https://www.coraltg.com/", img: "coraltg.png" },
  { title: "Körfez Ulaştırma", href: "https://www.korfezulastirma.com.tr/", img: "korfezulastirma.png" },
  { title: "Odeonbeds", href: "https://odeonbeds.com/", img: "odeonbedslogo.png" },
  { title: "Odeonbeds B2B", href: "https://b2b.odeonbeds.com/HomeV2/Login?ReturnUrl=%2F", img: "odeonbedslogonew.png" },
  { title: "Pixelplus", href: "https://www.pixelplus.net/", img: "pixelplus.png" },
  { title: "Odeontechnology", href: "https://www.odeontechnology.com/", img: "odeontechnology.png" },
  { title: "Profilo", href: "https://www.profilo.com/", img: "profilo.png" },
  { title: "Sunmar", href: "https://www.sunmar.ru/", img: "sunmar.png" },
  { title: "Tech Square", href: "https://www.techsquare.com.tr/", img: "techsquare.png" },
  { title: "Tivibu", href: "https://www.tivibu.com.tr/", img: "tivibu.png" },
  { title: "Türk Telekom Ödeme Hizmetleri", href: "https://www.turktelekomodemehizmetleri.com/", img: "turktelekomodemehizmetleri.png" },
  { title: "Tüyap", href: "https://tuyap.com.tr/", img: "tuyap.png" },
  { title: "Volkswagen Ticari Araç", href: "https://ticariarac.vw.com.tr/ana-sayfa", img: "vwticariarac.png" },
  { title: "Türkiye Bağımlılık Dizini", href: "https://bagimlilikdizini.yesilay.org.tr/", img: "bagimlilikdizini.png" },
  { title: "Mondihome", href: "https://www.mondihome.com.tr/", img: "mondihome.png" },
  { title: "Vdf Filo", href: "https://www.vdffilo.com.tr/", img: "vdffilo.png" },
  { title: "Tradeall", href: "https://www.tradeall.com/", img: "tradeall.png" },
  { title: "Boyteks", href: "https://www.boyteks.com/", img: "boyteks.png" },
  { title: "Akıllı Hayat", href: "https://www.zorlu.com.tr/akillihayat2030/", img: "akillihayat.png" },
  { title: "Bkt", href: "https://www.bkt.com.al/", img: "bkt.png" },
  { title: "Bellona", href: "https://www.bellona.com.tr/", img: "bellona.png" },
  { title: "Kayseri Belediyesi", href: "https://www.kayseri.bel.tr/", img: "kayseribel.png" },
  { title: "Garantikadingirisimci", href: "https://www.garantibbvakadingirisimci.com/", img: "garantikadingirisimci.png" },
  { title: "Americanexpress", href: "https://www.americanexpress.com.tr/", img: "americanexpress.png" },
  { title: "Yesilay", href: "https://www.yesilay.org.tr/tr/", img: "yesilay.png" },
  { title: "Tariszeytinyagi", href: "http://www.tariszeytinyagi.com/www.tariszeytinyagi.com/index.html", img: "tariszeytinyagi.png" },
];
