export const projectData = [
  {
    title: "Form Sünger",
    titlelink: "FormSunger",
    img: "FormSunger.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.formsunger.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Boyteks",
    titlelink: "Boyteks",
    img: "Boyteks.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.boyteks.com/",
    made: "Pixelplus",
  },
  {
    title: "Portfolio",
    titlelink: "Portfolio",
    img: "Portfolio.png",
    language: "React",
    tag: "React, Hook, Scss, Lazy-Suspense, React.memo",
    category: "react",
    link: "https://tolgakurtulus.github.io/Portfolio/",
    made: "HomeOffice",
  },
  {
    title: "Go Türkiye",
    titlelink: "Goturkiye",
    img: "Goturkiye.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://goturkiye.com/",
    made: "Pixelplus",
  },
  {
    title: "Erciyes Anadolu",
    titlelink: "Erciyesanadolu",
    img: "Erciyesanadolu.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.erciyesanadolu.com/",
    made: "Pixelplus",
  },
  {
    title: "Ticari Araç",
    titlelink: "Ticariarac",
    img: "Ticariarac.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://ticariarac.vw.com.tr/ana-sayfa",
    made: "Pixelplus",
  },
  {
    title: "Volkswagen",
    titlelink: "Volkswagen",
    img: "Volkswagen.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.vw.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Koç Sistem",
    titlelink: "Kocsistem",
    img: "Kocsistem.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.kocsistem.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Opet Fuchs",
    titlelink: "Opetfuchs",
    img: "Opetfuchs.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.opetfuchs.com.tr/tr/",
    made: "Pixelplus",
  },
  {
    title: "Yeşilay",
    titlelink: "Yesilay",
    img: "Yesilay.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.yesilay.org.tr/tr/",
    made: "Pixelplus",
  },
  {
    title: "Odeonbeds",
    titlelink: "Odeonbeds",
    img: "Odeonbeds.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://odeonbeds.com/",
    made: "Odeon Software & Technology",
  },
  {
    title: "Türkiye Bağımlılık Dizini",
    titlelink: "TurkiyeBagimlilikDizini",
    img: "TurkiyeBagimlilikDizini.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://bagimlilikdizini.yesilay.org.tr/",
    made: "Pixelplus",
  },
  {
    title: "Petrol Ofisi",
    titlelink: "PetrolOfisi",
    img: "PetrolOfisi.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.petrolofisi.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Pixelplus",
    titlelink: "Pixelplus",
    img: "Pixelplus.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.pixelplus.net/",
    made: "Pixelplus",
  },
  {
    title: "Ak Yatırım",
    titlelink: "AkYatirim",
    img: "AkYatirim.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.akyatirim.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Bonus",
    titlelink: "Bonus",
    img: "Bonus.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.bonus.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Weavers",
    titlelink: "Weavers",
    img: "Weavers.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.weavers.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Sütaş",
    titlelink: "Sutas",
    img: "Sutas.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.sutas.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Zorlu",
    titlelink: "Zorlu",
    img: "Zorlu.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.zorlu.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Sunmar",
    titlelink: "Sunmar",
    img: "Sunmar.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://www.sunmar.ru/",
    made: "Odeon Software & Technology",
  },
  {
    title: "Tüpraş",
    titlelink: "Tupras",
    img: "Tupras.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.tupras.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Boytrans",
    titlelink: "Boytrans",
    img: "Boytrans.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.boytrans.com.tr/tr/",
    made: "Pixelplus",
  },
  {
    title: "Tradeall",
    titlelink: "Tradeall",
    img: "Tradeall.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.tradeall.com/",
    made: "Pixelplus",
  },
  {
    title: "Albaraka",
    titlelink: "Albaraka",
    img: "Albaraka.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.albaraka.com.tr/tr",
    made: "Pixelplus",
  },
  {
    title: "Amerikan Express",
    titlelink: "Amerikanexpress",
    img: "Americanexpress.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.americanexpress.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Bkt",
    titlelink: "Bkt",
    img: "Bkt.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.bkt.com.al/",
    made: "Pixelplus",
  },
  {
    title: "Bonus Piu",
    titlelink: "BonusPiu",
    img: "BonusPiu.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.bonuspiu.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Boypas",
    titlelink: "Boypas",
    img: "Boypas.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.boypas.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Boyser",
    titlelink: "Boyser",
    img: "Boyser.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.boyser.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Doga Mağzaları",
    titlelink: "DogaMagzalari",
    img: "DogaMagzalari.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.dogamagazalari.com/",
    made: "Pixelplus",
  },
  {
    title: "Doqu Home",
    titlelink: "DoquHome",
    img: "DoquHome.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.doquhome.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Emlak Bankası",
    titlelink: "EmlakBankasi",
    img: "EmlakBankasi.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://emlakkatilim.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Gümüşsuyu Halı",
    titlelink: "GumussuyuHali",
    img: "GumussuyuHali.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.gumussuyu.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Hes Kablo",
    titlelink: "HesKablo",
    img: "HesKablo.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.hes.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Kalkınma Bankası",
    titlelink: "KalkinmaBankasi",
    img: "KalkinmaBankasi.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://kalkinma.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Kayseri Belediyesi",
    titlelink: "KayseriBelediyesi",
    img: "KayseriBelediyesi.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.kayseri.bel.tr/",
    made: "Pixelplus",
  },
  {
    title: "Körfez Ulaştırma",
    titlelink: "KorfezUlastirma",
    img: "KorfezUlastirma.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.korfezulastirma.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Mondi Home",
    titlelink: "MondiHome",
    img: "MondiHome.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.mondihome.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Türsab",
    titlelink: "Tursab",
    img: "Tursab.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.tursab.org.tr/",
    made: "Pixelplus",
  },
  {
    title: "Tüyap",
    titlelink: "Tuyap",
    img: "Tuyap.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://tuyap.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Garantibbva",
    titlelink: "Garantibbva",
    img: "Garantibbva.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.garantibbva.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Profilo",
    titlelink: "Profilo",
    img: "Profilo.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.profilo.com/",
    made: "Pixelplus",
  },
  {
    title: "Tech Square",
    titlelink: "Techsquare",
    img: "Techsquare.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.techsquare.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Tivibu",
    titlelink: "Tivibu",
    img: "Tivibu.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.tivibu.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Türk Telekom Ödeme Hizmetleri",
    titlelink: "Turktelekomodemehizmetleri",
    img: "Turktelekomodemehizmetleri.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.turktelekomodemehizmetleri.com/",
    made: "Pixelplus",
  },
  {
    title: "Vdf Filo",
    titlelink: "Vdffilo",
    img: "Vdffilo.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.vdffilo.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Akıllı Hayat 2030",
    titlelink: "Akillihayat2030",
    img: "Akillihayat2030.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.zorlu.com.tr/akillihayat2030/",
    made: "Pixelplus",
  },
  {
    title: "Bellona",
    titlelink: "Bellona",
    img: "Bellona.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.bellona.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Garantibbva Kadın Girişimci",
    titlelink: "Garantibbvakadingirisimci",
    img: "Garantibbvakadingirisimci.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.garantibbvakadingirisimci.com/",
    made: "Pixelplus",
  },
  {
    title: "American Express",
    titlelink: "Americanexpress",
    img: "Americanexpress.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.americanexpress.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Tariş Zeytinyaği",
    titlelink: "Tariszeytinyagi",
    img: "Tariszeytinyagi.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "http://www.tariszeytinyagi.com/www.tariszeytinyagi.com/index.html",
    made: "Pixelplus",
  },
  {
    title: "Ziraat Katılım",
    titlelink: "Ziraatkatilim",
    img: "Ziraatkatilim.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.ziraatkatilim.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "İstikbal",
    titlelink: "İstikbal",
    img: "İstikbal.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.istikbal.com.tr/",
    made: "Pixelplus",
  },
  {
    title: "Binek Arac",
    titlelink: "Binekarac",
    img: "Binekarac.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://binekarac.vw.com.tr/tr.html",
    made: "Pixelplus",
  },
  {
    title: "Garantibbva Ticari Kartlar",
    titlelink: "Garantibbvaticarikartlar",
    img: "Garantibbvaticarikartlar.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.garantibbvaticarikartlar.com/",
    made: "Pixelplus",
  },
  {
    title: "Türk Telekom Prime",
    titlelink: "Turktelekomprime",
    img: "Turktelekomprime.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.turktelekomprime.com/",
    made: "Pixelplus",
  },
  {
    title: "Coraltg",
    titlelink: "Coraltg",
    img: "Coraltg.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://www.coraltg.com/",
    made: "Odeon Software & Technology",
  },
  {
    title: "B2B Odeonbeds",
    titlelink: "B2bodeonbeds",
    img: "B2bodeonbeds.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://b2b.odeonbeds.com/HomeV2/Login?ReturnUrl=%2F",
    made: "Odeon Software & Technology",
  },
  {
    title: "Odeon Technology",
    titlelink: "Odeontechnology",
    img: "Odeontechnology.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://www.odeontechnology.com/",
    made: "Odeon Software & Technology",
  },
  {
    title: "Coral Travel",
    titlelink: "Coraltravel",
    img: "Coraltravel.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://www.coraltravel.com/",
    made: "Odeon Software & Technology",
  },
  {
    title: "Backoffice Odeonbeds",
    titlelink: "Backofficeodeonbeds",
    img: "Backofficeodeonbeds.png",
    tag: "Html, Css, Javascript, React, Redux, Scss",
    link: "https://backoffice.odeonbeds.com/",
    made: "Odeon Software & Technology",
  },
  {
    title: "Hediyelik Karakalem",
    titlelink: "HediyelikKarakalem",
    img: "HediyelikKarakalem.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.hediyelikkarakalem.com/",
    made: "HomeOffice",
  },
  {
    title: "Centurion",
    titlelink: "Centurion",
    img: "Centurion.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.americanexpress.com/en-us/account/centurion/login?DestPage=https%3A%2F%2Fwww.americanexpress.com%2Fus%2Fbenefits%2Fcenturion",
    made: "Pixelplus",
  },
  {
    title: "Canmarketings",
    titlelink: "Canmarketings",
    img: "canmarketings.png",
    tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
    link: "https://www.canmarketings.com/",
    made: "HomeOffice",
  },
  // {
  //   title: "Testtt",
  //   titlelink: "Testtt",
  //   img: "Testtt.png",
  //   
  //   tag: "Html, Css, Javascript, Jquery, Pug, Gulp, Webpack, Scss",
  //   
  //   link: "Testtt",
  //   made: "Pixelplus",
  // },
];

export const skillData = [
  { title: "Html", img: "html.png" },
  { title: "Css", img: "css.png" },
  { title: "Javascript", img: "javascript.png" },
  { title: "JQuery", img: "jquery.png" },
  { title: "React", img: "react.png" },
  { title: "Redux", img: "redux.png" },
  { title: "Sass", img: "sass.png" },
  { title: "Bootsrap", img: "bootstrap.png" },
  { title: "Material UI", img: "materialui.png" },
  { title: "Ant Design", img: "antd.png" },
  { title: "Bitbucket", img: "bitbucket.png" },
  { title: "Nextjs", img: "nextjs.png" },
  { title: "Git", img: "git.png" },
  { title: "Github", img: "github.png" },
  { title: "Gitlab", img: "gitlab.png" },
  { title: "Jira", img: "jira.png" },
  { title: "Pug", img: "pug.png" },
  { title: "Sdlc", img: "sdlc.png" },
  { title: "Next UI", img: "nextui.png" },
  { title: "DevExpress ", img: "devexpress.png" },
  { title: "Npm", img: "npm.png" },
  { title: "Yarn", img: "yarn.png" },
  { title: "Responsive", img: "responsive.png" },
  { title: "Agile", img: "agile.png" },
];

export const brandData = [
  {
    title: "Coral Travel",
    href: "https://www.coraltravel.com/",
    img: "coraltravel.png",
  },
  {
    title: "Ziraat Katilim",
    href: "https://www.ziraatkatilim.com.tr/",
    img: "ziraatkatilim.png",
  },
  {
    title: "İstikbal",
    href: "https://www.istikbal.com.tr/",
    img: "istikbal.png",
  },
  {
    title: "Emlak Katilim",
    href: "https://www.emlakkatilim.com.tr/",
    img: "emlakkatilim.png",
  },
  { title: "Zorlu", href: "https://www.zorlu.com.tr/", img: "zorlu.png" },
  {
    title: "Bonus Piu",
    href: "https://www.bonuspiu.com.tr/",
    img: "bonuspiu.png",
  },
  {
    title: "Koç Sistem",
    href: "https://www.kocsistem.com.tr/",
    img: "kocsistem.png",
  },
  { title: "Tüpraş", href: "https://www.tupras.com.tr/", img: "tupras.png" },
  {
    title: "Opet Fuchs",
    href: "https://www.opetfuchs.com.tr/tr/",
    img: "opetfuchs.png",
  },
  { title: "GoTurkiye", href: "https://goturkiye.com/", img: "goturkey.png" },
  {
    title: "Hediyelik Karakalem",
    href: "https://www.hediyelikkarakalem.com/",
    img: "hediyelikkarakalem.png",
  },
  {
    title: "Volkswagen",
    href: "https://www.vw.com.tr/",
    img: "volkswagen.png",
  },
  {
    title: "Erciyes Anadolu Holding",
    href: "https://www.erciyesanadolu.com/",
    img: "erciyesanadolu.png",
  },
  { title: "Hes Kablo", href: "https://www.hes.com.tr/", img: "heskablo.png" },
  { title: "Sütaş", href: "https://www.sutas.com.tr/", img: "sutas.png" },
  { title: "Bonus", href: "https://www.bonus.com.tr/", img: "bonus.png" },
  {
    title: "Doqu Home",
    href: "https://www.doquhome.com.tr/",
    img: "doquhome.png",
  },
  {
    title: "Akyatırım",
    href: "https://www.akyatirim.com.tr/",
    img: "akyatirim.png",
  },
  {
    title: "Garantibbva Ticari Kartlar",
    href: "https://www.garantibbvaticarikartlar.com/",
    img: "garantiticarikartlar.png",
  },
  {
    title: "Türk Telekom Prime",
    href: "https://www.turktelekomprime.com/",
    img: "turktelekomprime.png",
  },
  {
    title: "Kalkınma Yatırım Bankası",
    href: "https://kalkinma.com.tr/",
    img: "kalkinma.png",
  },
  {
    title: "Gümüşsuyu Halı",
    href: "https://www.gumussuyu.com.tr/",
    img: "gumusuyu.png",
  },
  {
    title: "Centurion",
    href: "https://www.americanexpress.com/en-us/account/centurion/login?DestPage=https%3A%2F%2Fwww.americanexpress.com%2Fus%2Fbenefits%2Fcenturion",
    img: "centurion.png",
  },
  {
    title: "Garantibbva",
    href: "https://www.garantibbva.com.tr/",
    img: "garantibbva.png",
  },
  { title: "Coraltg", href: "https://www.coraltg.com/", img: "coraltg.png" },
  {
    title: "Körfez Ulaştırma",
    href: "https://www.korfezulastirma.com.tr/",
    img: "korfezulastirma.png",
  },
  {
    title: "Odeonbeds",
    href: "https://odeonbeds.com/",
    img: "odeonbedslogo.png",
  },
  {
    title: "Odeonbeds B2B",
    href: "https://b2b.odeonbeds.com/HomeV2/Login?ReturnUrl=%2F",
    img: "odeonbedslogonew.png",
  },
  {
    title: "Pixelplus",
    href: "https://www.pixelplus.net/",
    img: "pixelplus.png",
  },
  {
    title: "Odeontechnology",
    href: "https://www.odeontechnology.com/",
    img: "odeontechnology.png",
  },
  { title: "Profilo", href: "https://www.profilo.com/", img: "profilo.png" },
  { title: "Sunmar", href: "https://www.sunmar.ru/", img: "sunmar.png" },
  {
    title: "Tech Square",
    href: "https://www.techsquare.com.tr/",
    img: "techsquare.png",
  },
  { title: "Tivibu", href: "https://www.tivibu.com.tr/", img: "tivibu.png" },
  {
    title: "Türk Telekom Ödeme Hizmetleri",
    href: "https://www.turktelekomodemehizmetleri.com/",
    img: "turktelekomodemehizmetleri.png",
  },
  { title: "Tüyap", href: "https://tuyap.com.tr/", img: "tuyap.png" },
  {
    title: "Volkswagen Ticari Araç",
    href: "https://ticariarac.vw.com.tr/ana-sayfa",
    img: "vwticariarac.png",
  },
  {
    title: "Türkiye Bağımlılık Dizini",
    href: "https://bagimlilikdizini.yesilay.org.tr/",
    img: "bagimlilikdizini.png",
  },
  {
    title: "Mondihome",
    href: "https://www.mondihome.com.tr/",
    img: "mondihome.png",
  },
  {
    title: "Vdf Filo",
    href: "https://www.vdffilo.com.tr/",
    img: "vdffilo.png",
  },
  { title: "Tradeall", href: "https://www.tradeall.com/", img: "tradeall.png" },
  { title: "Boyteks", href: "https://www.boyteks.com/", img: "boyteks.png" },
  {
    title: "Akıllı Hayat",
    href: "https://www.zorlu.com.tr/akillihayat2030/",
    img: "akillihayat.png",
  },
  { title: "Bkt", href: "https://www.bkt.com.al/", img: "bkt.png" },
  { title: "Bellona", href: "https://www.bellona.com.tr/", img: "bellona.png" },
  {
    title: "Kayseri Belediyesi",
    href: "https://www.kayseri.bel.tr/",
    img: "kayseribel.png",
  },
  {
    title: "Garantikadingirisimci",
    href: "https://www.garantibbvakadingirisimci.com/",
    img: "garantikadingirisimci.png",
  },
  {
    title: "Americanexpress",
    href: "https://www.americanexpress.com.tr/",
    img: "americanexpress.png",
  },
  {
    title: "Yesilay",
    href: "https://www.yesilay.org.tr/tr/",
    img: "yesilay.png",
  },
  {
    title: "Tariszeytinyagi",
    href: "http://www.tariszeytinyagi.com/www.tariszeytinyagi.com/index.html",
    img: "tariszeytinyagi.png",
  },
];
